[package]
name = "thesia"
version = "0.1.0"
authors = ["Sytronik <sytronik210@gmail.com>", "crackyachae <crackyache@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/Sytronik/thesia"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src_rust/lib.rs"

[dependencies]
ndarray = { version = "0.14.0", features = ["rayon", "approx"] }
rayon = "1.5.0"
num-traits = "0.2.14"
rustfft = "4.0.0"
rodio = { version = "0.13.0", default-features = false, features=["flac", "vorbis", "wav"] }
hound = "3.4.0"
image = "0.23.12"
wasm-bindgen = "0.2.69"
approx = {version = "0.4.0", features = ["num-complex"] }

[dependencies.ndarray-stats]
git = "https://github.com/rust-ndarray/ndarray-stats.git"
rev = "74a818026aca7c3ed40a3de09c779d225f3eef67"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
criterion = "0.3"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[[bench]]
name = "bench"
harness = false