[package]
authors = ["Sytronik <sytronik210@gmail.com>", "crackyachae <crackyache@gmail.com>"]
edition = "2018"
license = "MIT"
name = "thesia-native-backend"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
path = "native/lib.rs"

[dev-dependencies]
image = "0.23.12"

[dependencies]
napi = {version = "1.1.0", features = ["napi7"]}
napi-derive = "1.0.0"

approx = {version = "0.4.0", features = ["num-complex"]}
hound = "3.4.0"
lazy_static = "1.4.0"
ndarray = {version = "0.14.0", features = ["rayon", "approx"]}
num-traits = "0.2.14"
rayon = "1.5.0"
readonly = "0.2"
resize = "0.5.5"
rodio = "0.13.0"
rustfft = "5.0.0"
tiny-skia = "0.4.0"

[dependencies.ndarray-stats]
git = "https://github.com/rust-ndarray/ndarray-stats.git"
rev = "74a818026aca7c3ed40a3de09c779d225f3eef67"

[target.'cfg(all(unix, not(target_env = "musl"), not(target_arch = "aarch64")))'.dependencies]
jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}

[target.'cfg(all(windows, target_arch = "x86_64"))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1.0.1"

[profile.release]
codegen-units = 1
