[package]
name = "multi-spectrogram-viewer"
version = "0.1.0"
authors = ["Sytronik Liu <sytronik210@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ndarray = "0.14.0"
ndarray = { version = "0.13.0", features = ["rayon", "approx"] }
ndarray-stats = "0.3.0"
rayon = "1.5.0"
# blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
num-traits = "0.2.11"
rustfft = "4.0.0"
rodio = "0.13.0"
hound = "3.4.0"
