[package]
authors = ["Sytronik <sytronik210@gmail.com>", "crackyachae <crackyache@gmail.com>"]
edition = "2018"
license = "MIT"
name = "thesia-native-backend"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
path = "native/lib.rs"

[dev-dependencies]
image = "0.23.12"

[dependencies]
napi = "1.6.0"
napi-derive = "1.1.0"

cached = "0.23.0"
cpal = "0.13.1"
lazy_static = "1.4.0"
ndarray = {version = "0.15.1", features = ["rayon", "approx"]}
ndarray-stats = "0.5.0"
num-traits = "0.2.14"
rayon = "1.5.0"
readonly = "0.2"
rustfft = "6.0.0"
tiny-skia = "0.5.1"

[dependencies.approx]
features = ["num-complex"]
git = "https://github.com/brendanzab/approx.git"
rev = "195a9584bd7cb095cb09d0b37df22553cb08cc0a"

[dependencies.resize]
git = "https://github.com/Sytronik/resize.git"
rev = "51fd0b7c4c73c0051cfdfab2c3e963312b588789"

[dependencies.rodio]
git = "https://github.com/Sytronik/rodio.git"
rev = "209dd4c3587c9828d9b3eb3075fe449b41cf9353"

[target.'cfg(all(unix, not(target_env = "musl"), not(target_arch = "aarch64")))'.dependencies]
jemallocator = {version = "0.3.2", features = ["disable_initial_exec_tls"]}

[target.'cfg(all(windows, target_arch = "x86_64"))'.dependencies]
mimalloc = {version = "0.1.25"}

[build-dependencies]
napi-build = "1.0.2"

[profile.release]
codegen-units = 1
